### PR TITLE
Remove nv-peer-mem

### PR DESCRIPTION
**Pull request by rollandf**

### CODE REVIEW

**Review by adrianchiris — APPROVED** [review]

**Review by ykulazhenkov — COMMENTED** [review]
Hey, @rollandf thanks for the PR.
Did you test the upgrade flow? 
Will crd autougrade hook apply upgraded CRD correctly?

**Comment by rollandf** [comment]
> Hey, @rollandf thanks for the PR. Did you test the upgrade flow? Will crd autougrade hook apply upgraded CRD correctly?

@ykulazhenkov I tested upgrade and the CRD is updated.

**Review by ykulazhenkov — APPROVED** [review]

**Pull request merged**
