### PR TITLE
Use upstream SR-IOV Network Operator chart

### PR DESCRIPTION
**Pull request by e0ne**

### CODE REVIEW

**Comment by e0ne** [comment]
We need to wait for https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/167 and a new image or use older SR-IOV operator

**Comment by AbdYsn** [comment]
@e0ne The kind CI is failing because it is trying to read the sriov-operator images from the old values file, and because it is deleted, it is failing. A change in the CI will need to be done for this to work.

**Comment by AbdYsn** [comment]
@e0ne does this PR change the way to deploy the sriov-operator? also is it okay to use the upstream images for the sriov operator?

**Comment by moshe010** [comment]
@AbdYsn  what is the status of the CI workaround?  we want to  merge it ASAP

**Review by moshe010 — APPROVED** [review]

**Pull request merged**
