### PR TITLE
Update operator-sdk to 1.3.0

### LINKED ISSUE #33: [Enhancement] Update to operator-SDK v1.X
V1 of operator-sdk is out, we should use it.

### PR DESCRIPTION
**Pull request by Mmduh-483**
Fixes #33

### CODE REVIEW

**Comment by adrianchiris** [comment]
Can you rebase your PR so conflicts are resolved ?

Generally it seems ok however a few issues i encountered;

1. we should not maintain duplicated crds under deploy/ and under config/crd
2.  example folder should have up2date crds taken from config/crd or better yet remove them and update deploy/delete scripts to deploy the crds directly from their original directory WDYT?
3.  make image fails to build in my setup, does it work in yours ?
4. i noticed a few targets added in Makefile, do they work ?

also a general question:
did you use [this ](https://v1-3-x.sdk.operatorframework.io/docs/building-operators/golang/migration/)migration guide ?

**Comment by Mmduh-483** [comment]
> Can you rebase your PR so conflicts are resolved ?
udated


> 1. we should not maintain duplicated crds under deploy/ and under config/crd
not duplicated but auto-generated, as discussed it will be removed in a new commit and update the example

> 2. example folder should have up2date crds taken from config/crd or better yet remove them and update deploy/delete scripts to deploy the crds directly from their original directory WDYT?
it will be updated in new commit


> 3. make image fails to build in my setup, does it work in yours ?
The issue is related to the new test in `controllers/suite_test.go`, it fails in the `source` command because the `SHELL` default is `/bin/sh` which doesn't contain `source` (I used `.` but still fails with other errors if you check the latest ci failure)
`/bin/bash` doesn't exist in the docker image `golang/alpine`
currentlly trying to fix this issue

> 4. i noticed a few targets added in Makefile, do they work ?
yes


> also a general question:
> did you use [this ](https://v1-3-x.sdk.operatorframework.io/docs/building-operators/golang/migration/)migration guide ?
yes

**Comment by adrianchiris** [comment]
@Mmduh-483  i see nic_operator CI is failing

**Comment by Mmduh-483** [comment]
> @Mmduh-483 i see nic_operator CI is failing

@AbdYsn need to adjust the new updates since this PR replace the template in `deploy` by `example/deploy`

**Comment by adrianchiris** [comment]
So i  have reviewed this
a few nits and we are good to merge:

1. rename `deploy.sh` under `scripts` to `docker-push.sh` or similar as its confusing with deploy-operator.sh found there as well
2. remove `hack` folder as it contains no meaningful info
3. `README.md` L231 and L233 replace "Template" with "Example"
4. `example/README.md`  update Content section as it no longer contains the deploy/delete-operator
5. `example/README.md`  update setup cluster section, `make deploy` does not work when you are in example folder (change command to `make -C ./.. deploy`

**Comment by Mmduh-483** [comment]
> So i have reviewed this
> a few nits and we are good to merge once CI passes:
> 
> 1. rename `deploy.sh` under `scripts` to `docker-push.sh` or similar as its confusing with deploy-operator.sh found there as well
> 2. remove `hack` folder as it contains no meaningful info
> 3. `README.md` L231 and L233 replace "Template" with "Example"
> 4. `example/README.md`  update Content section as it no longer contains the deploy/delete-operator
> 5. `example/README.md`  update setup cluster section, `make deploy` does not work when you are in example folder (change command to `make -C ./.. deploy`

@adrianchiris  Updated the PR except for 2, `hack` has the `boilerplate.go.txt` which contain the header you want to be added to the auto-generated go files, in our case the license

**Review by adrianchiris — APPROVED** [review]

**Pull request merged**
