### PR TITLE
cicd: Release Network Operator v24.4.0-beta.1

### PR DESCRIPTION
**Pull request by nvidia-ci-cd**
Release Network Operator v24.4.0-beta.1

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Were we planning to cut a 24.1.1 beta before cutting the 24.4.0 beta?

**Review by e0ne — COMMENTED** [review]
CI issue isn't related to the change

**Comment by killianmuldoon** [comment]
> CI issue isn't related to the change

What's the CI issue?

**Pull request merged**
