### PR TITLE
Add Network Operator v1.1.0 bundle for OCP 4.9

### PR DESCRIPTION
**Pull request by e0ne**
Signed-off-by: Ivan Kolodiazhnyi <ikolodiazhny@nvidia.com>

### CODE REVIEW

**Comment by adrianchiris** [comment]
@AbdYsn @e0ne why does nic_operator_kind CI fails ?
This PR only adds OLM bundle files

**Comment by AbdYsn** [comment]
> @AbdYsn @e0ne why does nic_operator_kind CI fails ? This PR only adds OLM bundle files

there was an issue with hanging modules, handled it in the project, but there a small instability in the ci

**Pull request merged**
