### PR TITLE
Use NGC repository for Network Operator image

### PR DESCRIPTION
**Pull request by e0ne**
Signed-off-by: Ivan Kolodiazhny <ikolodiazhny@nvidia.com>

### CODE REVIEW

**Comment by AbdYsn** [comment]
@e0ne can you remove the depends-on from the commit message and upload the patch again?

**Review by moshe010 — APPROVED** [review]
@e0ne  Can I merge this?

**Comment by e0ne** [comment]
CI passed, it's good to be merged

**Pull request merged**
