### PR TITLE
Fix defaults in clusterserviceversion

### PR DESCRIPTION
**Pull request by adrianchiris**

### CODE REVIEW

**Comment by rollandf** [comment]
I thought that this file is generated by `make bundle` and that the examples are extracted from https://github.com/Mellanox/network-operator/blob/master/config/samples

**Comment by adrianchiris** [comment]
Fixed and updated commit msg.

there are still some values which needed to be overwritten in clusterserviceversion as they are not derived from config/samples

**Comment by adrianchiris** [comment]
WIP - as need to test on openshift cluster

**Review by rollandf — APPROVED** [review]

**Comment by adrianchiris** [comment]
Tested change on Openshift 4.12 it creates nicclusterpolicy by default without sriov network device plugin.

**Review by e0ne — APPROVED** [review]

**Pull request merged**
