### PR TITLE
V23.5.x add nv ipam

### PR DESCRIPTION
**Pull request by adrianchiris**
Cherry picks from v23.1.x-nv-ipam branch

### CODE REVIEW

**Review by e0ne — APPROVED** [review]
LGTM

**Comment by adrianchiris** [comment]
unit-test is failing because of a flaky test. this exist also in master.

**Comment by adrianchiris** [comment]
Discussed with our CI team, currently CI is not getting triggered on release branches ( they will fix)
it may have triggered here because of a bug. as i created and closed a similar pr against master, maybe it messed up the job.

they will add triggering for branches as well.

**Pull request merged**
