### PR TITLE
chore: Update SR-IOV Network Operator Helm chart

### PR DESCRIPTION
**Pull request by e0ne**
Update SR-IOV Network Operator Helm chart

### CODE REVIEW

**Comment by adrianchiris** [comment]
/lgtm 

just  making sure @e0ne these were copied as-is  from sriov-network-operator npwg proj ?

**Comment by e0ne** [comment]
> /lgtm
> 
> just making sure @e0ne these were copied as-is from sriov-network-operator npwg proj ?

yes, these CRDs are copied without any modifications

**Comment by adrianchiris** [comment]
is the helm chart updated in its entierty from upstream ? and not parts of it ?

**Comment by e0ne** [comment]
> is the helm chart updated in its entierty from upstream ? and not parts of it ?

the whole chart is updated now

**Review by rollandf — APPROVED** [review]

**Comment by rollandf** [comment]
Is it needed for v23.10 ?

**Comment by e0ne** [comment]
> Is it needed for v23.10 ?

yes, I'll cherry-pick this commit

**Pull request merged**
