### PR TITLE
chore: Align roles used in network operator

### PR DESCRIPTION
**Pull request by adrianchiris**
operator-sdk only generates cluster role
remove old role and rolebinding object to make things
consistent with operator-sdk generated files

### CODE REVIEW

**Comment by adrianchiris** [comment]
deployed a fully populated nicclusterpolicy as well as macvlan/ipoib/hostdevnetwork. seems to work as expected

```
network-operator   cni-plugins-ds-ddt7q                                              1/1     Running                      0               10m
network-operator   cni-plugins-ds-xwtlz                                              1/1     Running                      0               10m
network-operator   ib-kubernetes-57d8fddcdd-8sgk8                                    0/1     CreateContainerConfigError   0               46s
network-operator   kube-ipoib-cni-ds-mpqnd                                           1/1     Running                      0               10m
network-operator   kube-ipoib-cni-ds-xsgv8                                           1/1     Running                      0               10m
network-operator   kube-multus-ds-dhfpc                                              1/1     Running                      0               10m
network-operator   kube-multus-ds-ns6cs                                              1/1     Running                      0               10m
network-operator   mofed-ubuntu22.04-ds-k6zhm                                        0/1     Running                      0               4m54s
network-operator   mofed-ubuntu22.04-ds-md2ks                                        0/1     Running                      0               4m54s
network-operator   network-operator-6dcc764b84-g77vx                                 1/1     Running                      0               10m
network-operator   network-operator-node-feature-discovery-master-77fd94d8b8-shk6z   1/1     Running                      0               10m
network-operator   network-operator-node-feature-discovery-worker-5glxq              1/1     Running                      0               10m
network-operator   network-operator-node-feature-discovery-worker-vszv5              1/1     Running                      0               10m
network-operator   network-operator-node-feature-discovery-worker-ztfq7              1/1     Running                      0               10m
network-operator   nic-feature-discovery-ds-m9txr                                    1/1     Running                      0               10m
network-operator   nic-feature-discovery-ds-tcw7s                                    1/1     Running                      0               10m
network-operator   nv-ipam-controller-64c89dcfd5-mxdln                               1/1     Running                      0               10m
network-operator   nv-ipam-controller-64c89dcfd5-x94qv                               1/1     Running                      0               10m
network-operator   nv-ipam-node-bqw9q                                                1/1     Running                      0               10m
network-operator   nv-ipam-node-z9cr8                                                1/1     Running                      0               10m
network-operator   whereabouts-b6p4n                                                 1/1     Running                      0               10m
network-operator   whereabouts-ptb5v                                                 1/1     Running                      0               10m
```

note: ib-kubernetes fails as i didnt manually create the secret, not related to the operator.

**Comment by adrianchiris** [comment]
@rollandf PTAL, if you are happy with it, lets merge.

image scanning issue in ci is not related to this PR.

**Review by rollandf — APPROVED** [review]

**Pull request merged**
