### PR TITLE
chore: Update NFD version to v0.15.6

### PR DESCRIPTION
**Pull request by adrianchiris**

### CODE REVIEW

**Comment by adrianchiris** [comment]
we should hold with this until issue[1] is resolved, then update to a version that contains the fix.


[1] https://github.com/kubernetes-sigs/node-feature-discovery/issues/1752

**Comment by adrianchiris** [comment]
@e0ne this one is ready for review.

**Comment by adrianchiris** [comment]
helm CI fails for the folllowing reason:

```
fatal: [localhost]: FAILED! => {"changed": false, "command": "/usr/local/bin/helm upgrade -i --reset-values --wait --create-namespace --values=/tmp/k8s_1872430/artifacts/device-id-helm-values.yaml network-operator-helm-ci /tmp/k8s_1872430/mellanox-network-operator/deployment/network-operator", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/kubernetes/admin.conf\nWARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/kubernetes/admin.conf\nError: UPGRADE FAILED: failed to create patch: unable to find api field in struct Probe for the json field \"grpc\"\n", "stderr": "WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/kubernetes/admin.conf\nWARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/kubernetes/admin.conf\nError: UPGRADE FAILED: failed to create patch: unable to find api field in struct Probe for the json field \"grpc\"\n", "stderr_lines": ["WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/kubernetes/admin.conf", "WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/kubernetes/admin.conf", "Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct Probe for the json field \"grpc\""], "stdout": "", "stdout_lines": []}
```

our CI is using K8s 1.21.3 however grpc liveness/readiness probes were introduced in 1.23
kubernetes officially supports 1.27 as the oldest version.

**Comment by adrianchiris** [comment]
@e0ne updated helm on ci machine for nic-operator-helm-ci we can merge this one now IMO.

**Review by e0ne — APPROVED** [review]

**Review by rollandf — APPROVED** [review]

**Pull request merged**
