### PR TITLE
Fix bad indentation in ofed driver daemonset

### PR DESCRIPTION
**Pull request by adrianchiris**
Signed-off-by: Adrian Chiris <adrianc@nvidia.com>

### CODE REVIEW

**Comment by adrianchiris** [comment]
@AbdYsn LMK if i can merge this

**Comment by AbdYsn** [comment]
@adrianchiris i think it is ok to merge this, since the issue with the CI seems to be an issue with the new image

**Comment by adrianchiris** [comment]
Merged!

**Pull request merged**
