### PR TITLE
Update ofed image from ofed-driver to mofed with latest version

### PR DESCRIPTION
**Pull request by Mmduh-483**

### CODE REVIEW

**Comment by adrianchiris** [comment]
@Mmduh-483 we should wait with this until MOFED image is officially released,
In addition need to update README as well as other examples throughout the project.

**Comment by adrianchiris** [comment]
we should wait until an official version of mofed driver container is released

**Comment by adrianchiris** [comment]
GA driver container : mofed-5.2-1.0.4.0

**Comment by Mmduh-483** [comment]
@adrianchiris Updated

**Review by adrianchiris — APPROVED** [review]

**Pull request merged**
