### PR TITLE
chore: add tests to ipoib network state

### PR DESCRIPTION
**Pull request by rollandf**
Add tests to ipoib network state

### CODE REVIEW

**Review by ykulazhenkov — APPROVED** [review]

**Review by killianmuldoon — COMMENTED** [review]
We should probably clear up the discussion about which package the tests should be in i.e. https://github.com/Mellanox/network-operator/pull/814#discussion_r1494533813 before merging this.

**Comment by e0ne** [comment]
@rollandf  please, rebase this PR

**Comment by rollandf** [comment]
> @rollandf please, rebase this PR

Done

**Review by adrianchiris — APPROVED** [review]

**Pull request merged**
