### PR TITLE
chore: use stdlib slices

### PR DESCRIPTION
**Pull request by rollandf**
Use stdlib slices

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
/lgtm

Thanks for following up with this!

**Comment by killianmuldoon** [comment]
Looks like we're building with the wrong version of go - `make deploy` is failing in the kind test. Not sure how it's building as the Docker file is from go 1.21

**Comment by rollandf** [comment]
> Looks like we're building with the wrong version of go - `make deploy` is failing in the kind test. Not sure how it's building as the Docker file is from go 1.21

CI worker is 1.19
# go version
go version go1.19.2 linux/amd64

**Comment by killianmuldoon** [comment]
go compiler is used in `controller-gen` so it makes sense.

**Pull request merged**
