### PR TITLE
Use single namespace

### PR DESCRIPTION
**Pull request by rollandf**
In case the Network Operator is installed in OpenShift
via Operator Hub, the nvidia-network-operator-resources namespace
was not created automatically as with Helm.

With this patch, the Network Operator will create the underlying
resources in the same namespace it runs in.

Signed-off-by: Fred Rolland <frolland@nvidia.com>

### CODE REVIEW

**Review by e0ne — APPROVED** [review]
LGTM. deployment and upgrade verified manually

**Review by adrianchiris — APPROVED** [review]

**Comment by adrianchiris** [comment]
LGTM !

**Comment by adrianchiris** [comment]
@rollandf could you add a bit of a description in commit message on why this is needed ? 

then we can merge IMO

**Comment by rollandf** [comment]
> @rollandf could you add a bit of a description in commit message on why this is needed ?
> 
> then we can merge IMO

@adrianchiris done

**Pull request merged**
