### PR TITLE
Align nodeAffinity rules and default taints for managed components, add support for custom tolerations

### PR DESCRIPTION
**Pull request by ykulazhenkov**
- remove master and control-plane tolerations from
all DaemonSets
- remove anti affinity rules from DaemonSets
- add support to configure custom tolerations for components

### CODE REVIEW

**Review by e0ne — APPROVED** [review]

**Review by adrianchiris — COMMENTED** [review]
LGTM !

**Review by adrianchiris — APPROVED** [review]

**Comment by adrianchiris** [comment]
Hey,
this should be part of network operator release - 23.07 at around mid aug.

**Comment by tybritten** [comment]
Is there any workarounds in the meantime? I can't get the shared rdma DS to run with taints on.

**Comment by tybritten** [comment]
Any updates?

**Pull request merged**
